sudo: false

language: cpp

os:
- linux

addons:
  apt:
    packages:
    - automake
    - autoconf
    - cppcheck
    - g++
    - libboost-test-dev
    - make
    - valgrind

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
    - os: linux
      dist: trusty
      sudo: false

before_install:
- pip install --user cpp-coveralls

script:
- cppcheck
    --enable=performance,portability,information,style,missingInclude
    .
- autoreconf -if
- ./configure
- make
- valgrind
    --show-reachable=yes
    --leak-check=full
    make check

after_success:
- coveralls --gcov-options '\-lp'
