sudo: false

language: cpp

addons:
  apt:
    packages:
    - automake
    - autoconf
    - g++
    - libboost-test-dev
    - make
    - valgrind

script:
- autoreconf -if
- ./configure
- make
- valgrind
    --show-reachable=yes
    --leak-check=full
    make check
