sudo: required

language: cpp

before_install:
- sudo apt-get update
- sudo apt-get upgrade -y
- sudo apt-get install -y
    automake
    autoconf
    g++
    libboost-test-dev
    make

script:
- autoreconf
- ./configure
- make
- make check
